trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'

steps:
  - task: UseNode@1
    inputs:
      version: '$(NODE_VERSION)'

  - script: |
      npm ci
      npx tsc
    displayName: 'Install dependencies and build project'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-shomi-connection'
      appName: 'shomi'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
